GLOBAL_LIST_INIT(fatness_stage_to_BFI, list(
	"None" = FATNESS_LEVEL_NONE,
	"Rounded" = FATNESS_LEVEL_FAT,
	"Fat" = FATNESS_LEVEL_FATTER,
	"Very fat" = FATNESS_LEVEL_VERYFAT,
	"Obese" = FATNESS_LEVEL_OBESE,
	"Morbidly obese" = FATNESS_LEVEL_MORBIDLY_OBESE,
	"Extremely obese" = FATNESS_LEVEL_EXTREMELY_OBESE,
	"Barely mobile" = FATNESS_LEVEL_BARELYMOBILE,
	"Immobile" = FATNESS_LEVEL_IMMOBILE,
	"Fatty blob" = FATNESS_LEVEL_BLOB,
))

GLOBAL_LIST_INIT(fatness_stage_to_BFI_labeled, list(
	"None ([FATNESS_LEVEL_NONE])" = FATNESS_LEVEL_NONE,
	"Rounded ([FATNESS_LEVEL_FAT])" = FATNESS_LEVEL_FAT,
	"Fat ([FATNESS_LEVEL_FATTER])" = FATNESS_LEVEL_FATTER,
	"Very fat ([FATNESS_LEVEL_VERYFAT])" = FATNESS_LEVEL_VERYFAT,
	"Obese ([FATNESS_LEVEL_OBESE])" = FATNESS_LEVEL_OBESE,
	"Morbidly obese ([FATNESS_LEVEL_MORBIDLY_OBESE])" = FATNESS_LEVEL_MORBIDLY_OBESE,
	"Extremely obese ([FATNESS_LEVEL_EXTREMELY_OBESE])" = FATNESS_LEVEL_EXTREMELY_OBESE,
	"Barely mobile ([FATNESS_LEVEL_BARELYMOBILE])" = FATNESS_LEVEL_BARELYMOBILE,
	"Immobile ([FATNESS_LEVEL_IMMOBILE])" = FATNESS_LEVEL_IMMOBILE,
	"Fatty blob ([FATNESS_LEVEL_BLOB])" = FATNESS_LEVEL_BLOB,
))
